"""Tests for the opt-in figure layer (``nudge.viz``) — the first (dose-response) slice.

The load-bearing test is ``test_abstention_is_drawn_as_abstention``: a known abstention
must yield ``FigureResult.abstained is True`` AND draw the overlay — the honesty guarantee
that a polished figure can never claim more than the verdict. Real-data bits are marked
``needs_data``; everything else runs against a synthetic ``DoseResponseResult`` so the code
path is fully exercised with no external dataset.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("matplotlib")

import nudge.viz as viz  # noqa: E402
from nudge.inference.dose_response import attribute_dose_response  # noqa: E402


def _hill_repress(d, floor, amp, k, n):
    d = np.maximum(np.asarray(d, dtype=float), 1e-9)
    return floor + amp * k**n / (k**n + d**n)


def _switch_result():
    """A clean, resolved ultrasensitive switch (K inside the dose range)."""
    dose = np.linspace(0.0, 1.0, 16)
    resp = _hill_repress(dose, 0.1, 0.9, 0.5, 6.0)
    resp = resp + np.random.default_rng(0).normal(0.0, 0.01, dose.size)
    res = attribute_dose_response(dose, resp, direction="repress", n_boot=150, seed=0)
    assert res.call == "switch"
    return res, dose, resp


def _abstention_result():
    """A flat curve → the ``no-effect`` abstention (deterministic)."""
    dose = np.linspace(0.0, 0.6, 14)
    resp = 0.5 + np.random.default_rng(0).normal(0.0, 0.02, dose.size)
    res = attribute_dose_response(dose, resp, direction="repress", n_boot=150, seed=0)
    assert res.call in {"no-effect", "unresolved"}  # an abstention either way
    return res, dose, resp


def test_render_writes_png(tmp_path: Path) -> None:
    res, dose, resp = _switch_result()
    out = tmp_path / "fig.png"
    fr = viz.render(res, str(out), dose=dose, response=resp, label="SW")
    assert fr.path == str(out)
    assert out.exists() and out.stat().st_size > 0
    assert fr.kind == "dose_response"
    assert fr.abstained is False


def test_emits_provenance_code_and_data(tmp_path: Path) -> None:
    res, dose, resp = _switch_result()
    out = tmp_path / "fig.png"
    fr = viz.render(res, str(out), dose=dose, response=resp)
    assert fr.code_path is not None and Path(fr.code_path).exists()
    assert fr.data_path is not None and Path(fr.data_path).exists()
    header = Path(fr.code_path).read_text()
    assert "Generated by NUDGE viz" in header
    assert "emit_code=False" in header  # the replay must not re-emit code


def test_emitted_fig_py_reruns_and_reproduces(tmp_path: Path) -> None:
    """The standalone fig.py re-runs and reproduces the SAME figure (pixel-identical)."""
    res, dose, resp = _switch_result()
    out = tmp_path / "fig.png"
    viz.render(res, str(out), dose=dose, response=resp, label="SW")
    original = out.read_bytes()

    # Re-run the emitted script in a fresh working directory.
    replay_dir = tmp_path / "replay"
    replay_dir.mkdir()
    for name in ("fig.py", "fig.data.json"):
        (replay_dir / name).write_bytes((tmp_path / name).read_bytes())
    (replay_dir / "fig.png").unlink(missing_ok=True)
    proc = subprocess.run(
        [sys.executable, "fig.py"],
        cwd=replay_dir,
        capture_output=True,
        text=True,
        timeout=180,
    )
    assert proc.returncode == 0, proc.stderr
    replayed = (replay_dir / "fig.png").read_bytes()

    import matplotlib.image as mpimg

    a = mpimg.imread(str(out))
    b = mpimg.imread(str(replay_dir / "fig.png"))
    assert np.array_equal(a, b), "replayed figure differs from the original"
    # (byte-identity is the strong form; pixel-identity is the guarantee we assert)
    assert len(original) > 0 and len(replayed) > 0


def test_abstention_is_drawn_as_abstention(tmp_path: Path) -> None:
    """LOAD-BEARING honesty test: an abstention yields abstained=True + the overlay fires."""
    res, dose, resp = _abstention_result()

    # The FigureResult must report the abstention.
    fr = viz.render(res, str(tmp_path / "ab.png"), dose=dose, response=resp, label="AB")
    assert fr.abstained is True
    assert res.call.upper() in fr.caption.upper()

    # The overlay must actually be drawn on the panel (structural, not asserted-in-prose).
    rf = viz.figure(res, dose=dose, response=resp, label="AB")
    assert any(p.abstained for p in rf.panels)
    ax = rf.panels[0].ax
    assert getattr(ax, "_nudge_abstained", False) is True
    banners = [t.get_text() for t in ax.texts]
    assert any("CAN'T TELL" in b for b in banners), banners


def test_no_effect_panel_hides_k_label_and_places_banner_clear(tmp_path: Path) -> None:
    """Collision fix: an abstained panel must NOT assert a confident K under the banner.

    A ``no-effect`` fit can still have ``spans_inflection=True``; the renderer must suppress
    the "K … (inside range)" label there so it does not collide with the abstain banner in
    the reserved top band (Phase-0 overlap fix), and the banner must still fire.
    """
    res, dose, resp = _abstention_result()
    rf = viz.figure(res, dose=dose, response=resp, label="FLAT")
    ax = rf.panels[0].ax
    texts = [t.get_text() for t in ax.texts]
    assert not any("inside range" in t for t in texts), texts
    assert getattr(ax, "_nudge_abstained", False) is True
    assert any("CAN'T TELL" in t for t in texts), texts


def test_one_sided_bound_when_not_spanning(tmp_path: Path) -> None:
    """A K-past-the-dose-range (unresolved) panel draws the open-ended one-sided marker."""
    dose = np.linspace(0.0, 0.55, 15)
    resp = _hill_repress(dose, 0.3, 0.7, 0.95, 3.0)
    resp = resp + np.random.default_rng(1).normal(0.0, 0.01, dose.size)
    res = attribute_dose_response(dose, resp, direction="repress", n_boot=150, seed=0)
    if res.fit.spans_inflection:
        pytest.skip("this synthetic happened to span the inflection")
    rf = viz.figure(res, dose=dose, response=resp, label="ONE")
    assert rf.panels[0].one_sided is True
    assert getattr(rf.panels[0].ax, "_nudge_one_sided", False) is True


def test_dual_input_dataclass_and_dict(tmp_path: Path) -> None:
    """Both a frozen result dataclass and its dict form render (design §2.2 dual-input)."""
    res, dose, resp = _switch_result()

    # (a) the frozen dataclass.
    fr_obj = viz.render(res, str(tmp_path / "obj.png"), dose=dose, response=resp)
    assert Path(fr_obj.path or "").exists()

    # (b) the canonical figure-data dict (what fig.data.json carries).
    data = viz.dose_response.dose_response_data(("SW", res, dose, resp))
    assert data["kind"] == "dose_response"
    fr_dict = viz.render(data, str(tmp_path / "dict.png"))
    assert Path(fr_dict.path or "").exists()
    assert fr_dict.abstained is False

    # (c) the service *_to_dict() form renders too (curve-only when it lacks points).
    from nudge.service import dose_response_to_dict

    svc = dose_response_to_dict(res)
    fr_svc = viz.render(svc, str(tmp_path / "svc.png"), kind="dose_response")
    assert Path(fr_svc.path or "").exists()


def test_flagship_dual_panel(tmp_path: Path) -> None:
    """One frame: a resolved switch beside an honest abstention — the thesis, visualized."""
    sw, d1, r1 = _switch_result()
    ab, d2, r2 = _abstention_result()
    fr = viz.render(
        [("OCT4-like", sw, d1, r1), ("NANOG-like", ab, d2, r2)],
        str(tmp_path / "flagship.png"),
    )
    assert Path(fr.path or "").exists()
    assert fr.abstained is True  # the abstaining panel makes the figure carry a caveat


def test_self_contained_single_file(tmp_path: Path) -> None:
    res, dose, resp = _switch_result()
    out = tmp_path / "sc.png"
    fr = viz.render(
        res, str(out), dose=dose, response=resp, self_contained=True
    )
    assert fr.data_path is None  # data is inlined into the script
    assert fr.code_path is not None
    script = Path(fr.code_path).read_text()
    assert "_DATA" in script and "b64decode" in script


def test_service_render_result_seam(tmp_path: Path) -> None:
    from nudge.service import render_result

    res, dose, resp = _switch_result()
    d = render_result(
        "dose_response", res, out=str(tmp_path / "s.png"), dose=dose, response=resp
    )
    assert d["kind"] == "dose_response"
    assert d["abstained"] is False
    assert Path(d["png_path"]).exists()
    assert Path(d["code_path"]).exists()


@pytest.mark.needs_data
def test_real_oct4_nanog_flagship(tmp_path: Path) -> None:
    """The real ESC-screen flagship: OCT4 → switch beside NANOG → honest abstain."""
    import os

    import anndata as ad

    from nudge.inference.bridge import knockdown_dose_response

    h5ad = os.environ.get(
        "OCT4_NANOG_H5AD", "/media/nick/Seagate Hub/oct4_nanog/ESC.h5ad"
    )
    if not Path(h5ad).exists():
        pytest.skip(f"OCT4/NANOG data not present at {h5ad}")

    adata = ad.read_h5ad(h5ad)
    sig = ["SOX2", "LIN28A", "UTF1", "DNMT3B", "TDGF1", "ZFP42", "SALL4"]
    present = [g for g in sig if g in set(map(str, adata.var_names))]
    entries = []
    for label, gene in (("OCT4", "POU5F1"), ("NANOG", "NANOG")):
        dose, resp = knockdown_dose_response(
            adata, target_gene=gene, signature=present,
            group_prefix=label, min_cells_per_group=15,
        )
        res = attribute_dose_response(dose, resp, direction="repress", n_boot=200)
        entries.append((label, res, dose, resp))
    fr = viz.render(entries, str(tmp_path / "flagship.png"))
    assert fr.abstained is True  # NANOG abstains
    assert "OCT4" in fr.caption and "SWITCH" in fr.caption.upper()
    assert "NANOG" in fr.caption and "UNRESOLVED" in fr.caption.upper()
