"""Alzheimer's-disease amyloid-β QSP model — a differentiable JAX vector field.

**A real, published, open clinical model, made differentiable.** This module implements
the **amyloid-β aggregation subsystem** of the Proctor et al. 2013 Alzheimer's-disease
quantitative-systems-pharmacology model as a self-contained differentiable JAX ODE, so
NUDGE's white-box machinery — matrix-free population identifiability and gradient-based
optimal experimental design — can be pointed at a genuine clinical QSP structure.

Source model (CC0 public domain, BioModels ``BIOMD0000000488``):

    Proctor CJ, Boche D, Gray DA, Nicoll JAR. "Investigating interventions in Alzheimer's
    disease with computer simulation models." PLoS ONE 2013; 8(9):e73631.
    PMID 24098635 · DOI 10.1371/journal.pone.0073631.

The **full** 64-state Proctor network (Aβ + tau + p53/Mdm2 + ubiquitin–proteasome +
microglia) is transcribed **faithfully and in full** from the CC0 SBML into
``nudge.mechanisms._proctor2013`` (auto-generated by ``scripts/vv/gen_proctor2013.py``,
verified to parse and take gradients). That is the exact published model — the citation
anchor and the reaction-network ground truth.

**What THIS module integrates, and the honest bound.** The published parameterization is a
stochastic / stiff seconds-to-years system (rate constants span ``kpf=0.2`` to
``kaggAbeta=3e-6`` — a ~7e4 stiffness ratio) that was integrated in the original with
Gillespie / LSODA. An **explicit** fixed-step RK4 (NUDGE's differentiable ``lax.scan``
integrator; no ``diffrax``) cannot integrate it over disease timescales without an implicit
solver (measured: it diverges within days for any physiological monomer pool). So for the
differentiable demo this module keeps the **published reaction topology and rate-law forms**
— the autocatalytic Hill plaque-growth switch (threshold ``K_pg`` / gain ``k_pg``, the
Proctor ``AbetaPlaqueGrowth`` reaction), the monomer→oligomer→plaque aggregation cascade,
antibody PK/PD (dosing → target binding → clearance), and microglial plaque clearance — but
uses **non-dimensionalized, demo-scaled rate constants** chosen so an explicit differentiable
RK4 integrates the cascade stably. The identifiability *structure* NUDGE analyzes (which
rate constants are sloppy; which parameter pairs are confounded) is a property of the
rate-law forms, which are preserved. This scaling caveat is ``NUDGE-LIM-026``.

Additive / opt-in and self-contained: the differentiable RK4 (a ``lax.scan``) is
re-instantiated in-module; it touches **neither ``fit.py`` nor ``core/``** (the frozen-core
constraint). It reuses the identifiability grammar of :mod:`nudge.inference.sloppiness` and
the OED grammar of :mod:`nudge.inference.oed`.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

import jax
import jax.numpy as jnp
import numpy as np
from jax import Array

__all__ = [
    "AD_SPECIES",
    "AD_PARAM_NAMES",
    "AD_PARAM_VALUES",
    "AD_PARAM_DOC",
    "BIOMARKERS",
    "ad_field",
    "simulate_subject",
    "CohortProblem",
    "make_ad_cohort_predict_fn",
    "generate_ad_cohort",
    "make_ad_oed_problem",
]

# --------------------------------------------------------------------------- #
# the model: dimensionless Proctor-2013 Aβ-aggregation subsystem
# --------------------------------------------------------------------------- #
#: dynamic states of the differentiable subsystem.
AD_SPECIES: tuple[str, ...] = (
    "Abeta_monomer",     # M   — soluble Aβ monomer (Proctor `Abeta`)
    "Abeta_oligomer",    # O   — soluble oligomer / dimer (Proctor `AbetaDimer`)
    "Abeta_plaque",      # P   — aggregated plaque (Proctor `AbetaPlaque`)
    "antibody",          # A   — therapeutic anti-Aβ mAb (Proctor `antiAb`)
    "antibody_complex",  # C   — antibody-bound Aβ, cleared (Proctor `Abeta_antiAb`)
    "microglia",         # G   — activated microglia clearance capacity (Proctor `GliaA`)
)

#: the kinetic parameters (order = the free-parameter vector). Named after the Proctor
#: reactions they correspond to; values are dimensionless / demo-scaled (see module docstring
#: + ``NUDGE-LIM-026``), preserving the published rate-law forms and the confound structure.
AD_PARAM_NAMES: tuple[str, ...] = (
    "s_M",    # monomer production            (Proctor Abetaproduction1, kprodAbeta)
    "d_M",    # monomer degradation           (Proctor AbetaDegradation, kdegAbeta)
    "k_agg",  # monomer→oligomer aggregation  (Proctor AbetaAggregation1, kaggAbeta)
    "k_dis",  # oligomer→monomer disaggreg.   (Proctor AbetaDisaggregation1, kdisaggAbeta)
    "k_pf",   # oligomer→plaque formation     (Proctor AbetaPlaqueFormation1, kpf)
    "k_pg",   # plaque-growth GAIN (Hill)     (Proctor AbetaPlaqueGrowth, kpg)
    "K_pg",   # plaque-growth THRESHOLD (Hill)(Proctor AbetaPlaqueGrowth, kpghalf)
    "k_dp",   # plaque disaggregation         (Proctor AbetaDisaggregation3, kdisaggAbeta1)
    "k_on",   # antibody–Aβ binding affinity  (Proctor Abeta_antiAbBinding, kbinAbantiAb)
    "d_A",    # antibody clearance            (Proctor antiAbRemoval, kdegAntiAb)
    "k_gl",   # microglial plaque clearance   (Proctor AbetaPlaqueClearanceByGlia, kdegAbetaGlia)
    "k_ga",   # microglial activation by plaque(Proctor GliaActivationStep1, kactglia1)
)

#: demo-scaled nominal values (dimensionless). Tuned so the explicit RK4 cascade is a clean
#: bounded plaque sigmoid engaging the Hill switch, and antibody dosing measurably lowers
#: plaque — verified in ``tests/mechanisms/test_ad_qsp.py``.
AD_PARAM_VALUES: np.ndarray = np.array(
    [0.05, 0.05, 0.6, 0.12, 0.5, 1.3, 1.0, 0.06, 0.9, 0.5, 0.2, 0.35], dtype=np.float64
)

AD_PARAM_DOC: dict[str, str] = dict(zip(AD_PARAM_NAMES, (
    "Aβ monomer production (source)",
    "Aβ monomer degradation / clearance",
    "monomer→oligomer aggregation (2nd order)",
    "oligomer→monomer disaggregation",
    "oligomer→plaque formation (2nd order)",
    "autocatalytic plaque-growth GAIN (Hill numerator)",
    "autocatalytic plaque-growth THRESHOLD (Hill half-saturation)",
    "plaque disaggregation",
    "antibody–Aβ binding affinity",
    "antibody clearance rate",
    "microglial plaque clearance rate",
    "microglial activation by plaque",
), strict=True))

#: default seeded initial state (a physiological monomer pool; everything else 0).
AD_X0: np.ndarray = np.array([3.0, 0.0, 0.0, 0.0, 0.0, 0.0], dtype=np.float64)

#: default antibody dosing window (infusion on ``[t_on, t_off)``) — the transient that
#: separates the antibody-binding ⇄ clearance confound (see :func:`make_ad_oed_problem`).
DOSE_WINDOW: tuple[float, float] = (2.0, 8.0)

#: biomarker readouts (indices into :data:`AD_SPECIES`) — the observed clinical panel:
#: plaque load (≈ amyloid-PET) and soluble oligomer (≈ CSF Aβ). Cognition is not modelled
#: mechanistically here; plaque is the primary readout.
BIOMARKERS: tuple[int, ...] = (2, 1)  # Abeta_plaque, Abeta_oligomer
#: hard abundance cap inside the integrator (a diverging orbit → a bad design, not a NaN).
_X_CAP = 1e6
#: log-offset for the log-abundance observation transform (abundances ≥ 0, ≈ 0 in OFF state).
_LOG_OFFSET = 1e-3


def ad_field(x: Array, p: Array, u: Array) -> Array:
    """The differentiable Aβ-cascade vector field ``dx/dt = f(x, p, u)`` (RAW params ``p``).

    ``x`` = the six :data:`AD_SPECIES`; ``p`` = the 12 :data:`AD_PARAM_NAMES` (raw, positive);
    ``u`` = the scalar antibody-infusion input. The plaque-growth term
    ``k_pg·O·P²/(K_pg²+P²)`` is the published Proctor ``AbetaPlaqueGrowth`` autocatalytic Hill
    switch (gain ``k_pg`` / threshold ``K_pg``); the rest is the mass-action aggregation
    cascade + antibody binding/clearance + microglial clearance. Parameters are RAW (not
    log) so the sloppiness diagnostic's ``θ·∂/∂θ`` recovers the log-sensitivity, matching the
    :mod:`nudge.inference.sloppiness` / :mod:`nudge.inference.adjoint` convention.
    """
    M, Ol, Pl, A, C, G = x  # monomer, oligomer, plaque, antibody, complex, microglia
    s_M, d_M, k_agg, k_dis, k_pf, k_pg, K_pg, k_dp, k_on, d_A, k_gl, k_ga = (
        p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11]
    )
    r_agg = 0.5 * k_agg * M * M
    r_dis = k_dis * Ol
    r_pf = 0.5 * k_pf * Ol * Ol
    r_pg = k_pg * Ol * Pl * Pl / (K_pg * K_pg + Pl * Pl)  # Proctor AbetaPlaqueGrowth (Hill)
    r_dp = k_dp * Pl
    r_clr = k_gl * G * Pl
    dM = s_M - d_M * M - 2.0 * r_agg + 2.0 * r_dis - k_on * A * M
    dO = r_agg - r_dis - 2.0 * r_pf - k_on * A * Ol + r_dp
    dPl = r_pf + r_pg - r_dp - r_clr
    dA = u - d_A * A
    dC = k_on * A * (M + Ol) - 0.5 * d_A * C
    dG = k_ga * Pl * (1.0 - G) - 0.2 * G
    return jnp.stack([dM, dO, dPl, dA, dC, dG])


# --------------------------------------------------------------------------- #
# the differentiable RK4 integrator (a lax.scan; no diffrax) + observation
# --------------------------------------------------------------------------- #
def _dose_grid(grid_t: Array, dose: float, window: tuple[float, float]) -> Array:
    t_on, t_off = window
    return jnp.where((grid_t >= t_on) & (grid_t < t_off), dose, 0.0)


def _rk4_full(
    p: Array, x0: Array, grid_t: Array, u_grid: Array, dt: float
) -> Array:
    """Integrate ``dx/dt = ad_field(x, p, u)`` on the fine grid → full trajectory ``(G+1, 6)``.

    A plain RK4 ``lax.scan`` (differentiable w.r.t. ``p``); index 0 = ``t0`` so the trajectory
    can be interpolated at continuous observation times (the OED design ``φ``).
    """
    def step(x: Array, u: Array) -> tuple[Array, Array]:
        k1 = ad_field(x, p, u)
        k2 = ad_field(x + 0.5 * dt * k1, p, u)
        k3 = ad_field(x + 0.5 * dt * k2, p, u)
        k4 = ad_field(x + dt * k3, p, u)
        x_next = jnp.clip(x + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4), 0.0, _X_CAP)
        return x_next, x_next

    _final, traj = jax.lax.scan(step, x0, u_grid)
    return jnp.concatenate([x0[None, :], traj], axis=0)


def simulate_subject(
    p: Array | np.ndarray | None = None,
    *,
    dose: float = 0.0,
    t_max: float = 12.0,
    dt: float = 0.04,
    x0: np.ndarray | None = None,
    dose_window: tuple[float, float] = DOSE_WINDOW,
) -> tuple[np.ndarray, np.ndarray]:
    """Forward-simulate one subject → ``(trajectory (n+1, 6), times (n+1,))``.

    ``p`` defaults to :data:`AD_PARAM_VALUES`; ``dose`` is the antibody-infusion amplitude on
    ``dose_window``. Used for the sanity forward-sim (a bounded amyloid→plaque sigmoid; a
    nonzero dose lowers plaque) and the notebook.
    """
    p_arr = AD_PARAM_VALUES if p is None else np.asarray(p, dtype=np.float64)
    x0_arr = AD_X0 if x0 is None else np.asarray(x0, dtype=np.float64)
    n = int(round(t_max / dt))
    grid_t = np.arange(n) * dt
    u_grid = _dose_grid(jnp.asarray(grid_t), dose, dose_window)
    traj = _rk4_full(
        jnp.asarray(p_arr), jnp.asarray(x0_arr), jnp.asarray(grid_t), u_grid, dt
    )
    times = np.concatenate([[0.0], grid_t + dt])  # step i records time (i+1)·dt
    return np.asarray(traj), times


# --------------------------------------------------------------------------- #
# population-scale cohort: the calibration problem whose free-parameter count OOMs jacfwd
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class CohortProblem:
    """A synthetic subject-specific-parameter calibration problem (nonlinear mixed effects).

    ``predict_fn(theta) -> observations`` maps the **free** subject-specific (raw) parameter
    vector to the stacked biomarker observations over the whole cohort; ``theta0``
    is the true free-parameter vector, ``param_names`` labels it. The full stacked parameter
    set is ``n_subjects × len(AD_PARAM_NAMES)`` (each subject its own kinetics); the first
    ``n_free`` are free (differentiated w.r.t.), the rest held at truth — so ``n_free`` is a
    clean knob that grows the population calibration's dimensionality at **fixed** integrated
    state (all subjects always simulated), exactly the sweep that OOMs the dense ``jacfwd``
    sensitivity while the matrix-free FIM matvec stays flat.
    """

    predict_fn: Callable[[Array], Array]
    theta0: np.ndarray
    param_names: tuple[str, ...]
    n_subjects: int
    n_free: int
    n_obs: int
    n_states: int
    meta: dict[str, Any] = field(default_factory=dict)

    @property
    def n_theta(self) -> int:
        return int(self.theta0.shape[0])


def _cohort_params(n_subjects: int, seed: int, isv: float) -> np.ndarray:
    """Subject-specific parameters: population truth × log-normal inter-subject variability."""
    rng = np.random.default_rng(seed)
    base = AD_PARAM_VALUES[None, :]
    log_shift = isv * rng.standard_normal((n_subjects, AD_PARAM_VALUES.shape[0]))
    return base * np.exp(log_shift)  # (n_subjects, n_params) raw, positive


def make_ad_cohort_predict_fn(
    *,
    n_subjects: int = 60,
    n_free: int = 120,
    n_obs_times: int = 8,
    t_max: float = 12.0,
    dt: float = 0.06,
    dose: float = 0.6,
    isv: float = 0.15,
    biomarkers: tuple[int, ...] = BIOMARKERS,
    seed: int = 0,
) -> CohortProblem:
    """Build the population-calibration :class:`CohortProblem` (the identifiability target).

    Each of ``n_subjects`` subjects carries its own copy of the 12 AD kinetic parameters
    (population truth × ``isv`` log-normal inter-subject variability); the full stacked
    parameter vector has ``n_subjects × 12`` entries and the first ``n_free`` are free. The
    forward map ``vmap``\\s the single-subject RK4 solve over the cohort and returns the
    log-biomarker observations at ``n_obs_times`` times — a ``(n_subjects · n_obs_times ·
    len(biomarkers),)`` vector. Sweeping ``n_free`` at fixed cohort is the OOM benchmark's
    axis (:func:`nudge.mechanisms.ad_qsp` docstring); the FIM of this map is the population
    identifiability.
    """
    n_params = AD_PARAM_VALUES.shape[0]
    p_full = n_subjects * n_params
    n_free = int(np.clip(n_free, 1, p_full))

    subj_p = _cohort_params(n_subjects, seed, isv)  # (n_subjects, n_params)
    full = subj_p.reshape(-1)  # (n_subjects*n_params,)
    free_idx = np.arange(n_free)

    n = int(round(t_max / dt))
    grid_t = np.arange(n) * dt
    obs_t = np.linspace(0.0, t_max, n_obs_times)
    obs_idx = np.clip(np.round(obs_t / dt).astype(int), 0, n)  # index into (G+1) trajectory
    u_grid = np.asarray(_dose_grid(jnp.asarray(grid_t), dose, DOSE_WINDOW))
    x0 = np.tile(AD_X0, (n_subjects, 1))

    full_j = jnp.asarray(full)
    free_idx_j = jnp.asarray(free_idx)
    x0_j = jnp.asarray(x0)
    grid_j = jnp.asarray(grid_t)
    u_j = jnp.asarray(u_grid)
    obs_idx_j = jnp.asarray(obs_idx)
    biom_j = jnp.asarray(np.asarray(biomarkers))

    def one_subject(p_row: Array, x0_row: Array) -> Array:
        traj = _rk4_full(p_row, x0_row, grid_j, u_j, dt)  # (G+1, 6)
        obs = traj[obs_idx_j][:, biom_j]  # (n_obs_times, n_biom)
        return jnp.log(jnp.clip(obs, 0.0, _X_CAP) + _LOG_OFFSET).reshape(-1)

    def predict(theta: Array) -> Array:
        full_p = full_j.at[free_idx_j].set(theta.astype(full_j.dtype))
        P = full_p.reshape(n_subjects, n_params)
        obs = jax.vmap(one_subject)(P, x0_j)  # (n_subjects, n_obs_times*n_biom)
        return obs.reshape(-1)

    theta0 = full[free_idx]
    n_obs = int(n_subjects * n_obs_times * len(biomarkers))
    param_names = tuple(
        f"{AD_PARAM_NAMES[i % n_params]}[subj{i // n_params}]" for i in free_idx
    )
    return CohortProblem(
        predict_fn=predict,
        theta0=theta0.astype(np.float64),
        param_names=param_names,
        n_subjects=n_subjects,
        n_free=n_free,
        n_obs=n_obs,
        n_states=int(n_subjects * len(AD_SPECIES)),
        meta={"n_params_per_subject": n_params, "n_obs_times": n_obs_times,
              "biomarkers": biomarkers, "dose": dose, "isv": isv, "t_max": t_max, "dt": dt},
    )


def generate_ad_cohort(
    *,
    n_subjects: int = 60,
    n_obs_times: int = 12,
    dose: float = 0.6,
    isv: float = 0.15,
    obs_noise: float = 0.05,
    seed: int = 0,
) -> dict[str, Any]:
    """Generate a synthetic ground-truth cohort: subject-specific parameters + dense
    biomarker observations (the SYNTHETIC calibration target — never real patient data).

    Returns the true per-subject parameters and the (optionally noised) log-biomarker
    observations. This is the honest calibration cohort the identifiability analysis is
    *about*: a nonlinear-mixed-effects population whose subject-specific parameters are the
    thousands of free numbers that OOM a dense sensitivity matrix.
    """
    prob = make_ad_cohort_predict_fn(
        n_subjects=n_subjects, n_free=n_subjects * AD_PARAM_VALUES.shape[0],
        n_obs_times=n_obs_times, dose=dose, isv=isv, seed=seed,
    )
    clean = np.asarray(prob.predict_fn(jnp.asarray(prob.theta0)))
    rng = np.random.default_rng(seed + 1)
    noisy = clean + obs_noise * rng.standard_normal(clean.shape) if obs_noise > 0 else clean
    return {
        "true_params": prob.theta0.reshape(n_subjects, -1),
        "observations": noisy,
        "clean_observations": clean,
        "param_names": AD_PARAM_NAMES,
        "n_subjects": n_subjects,
        "n_obs_times": n_obs_times,
        "obs_noise": obs_noise,
        "note": "SYNTHETIC ground-truth cohort generated from the AD QSP model — NOT real "
                "patient data.",
    }


# --------------------------------------------------------------------------- #
# the OED problem: two confounded parameters + the measurement schedule
# --------------------------------------------------------------------------- #
def _observe_at(traj: Array, grid_t: Array, phi: Array, biom: Array) -> Array:
    """Interpolate a fine trajectory at continuous times ``phi`` and log the biomarkers."""
    cols = [jnp.interp(phi, grid_t, traj[:, int(s)]) for s in np.asarray(biom)]
    obs = jnp.stack(cols, axis=1)  # (m, n_biom)
    return jnp.log(jnp.clip(obs, 0.0, _X_CAP) + _LOG_OFFSET).reshape(-1)


def make_ad_oed_problem(
    *,
    target: str = "k_on",
    pair: tuple[str, str] = ("k_on", "k_gl"),
    t_max: float = 12.0,
    dt: float = 0.03,
    dose: float = 0.6,
    sigma: float = 0.05,
    t_min: float = 0.05,
    biomarkers: tuple[int, ...] = (2,),  # plaque only (≈ amyloid-PET): the realistic single readout
):
    """Build an :class:`nudge.inference.oed.DesignProblem` over the measurement schedule for
    a genuinely **confounded** parameter pair (default antibody binding ``k_on`` ⇄ microglial
    clearance ``k_gl``).

    Both parameters lower amyloid burden, so a naive late-only schedule confounds them
    (a near-singular FIM); the antibody **dosing transient** (on ``DOSE_WINDOW``) separates
    them — ``k_on`` acts only while the antibody is present, ``k_gl`` acts throughout — which
    the OED gradient discovers. ``theta`` = ``(log p_i, log p_j)`` for the pair, all other
    kinetics fixed at truth; ``φ`` = the vector of measurement times in ``[t_min, t_max]``.
    Returns a ``DesignProblem`` whose ``observe(theta, φ)`` integrates the dosed model and
    reads the biomarkers at ``φ`` (differentiable in both). The confound is *verified* by
    measuring the FIM correlation, never asserted (``NUDGE-LIM-024`` local OED).
    """
    from nudge.inference.oed import DesignProblem

    name_idx = {n: i for i, n in enumerate(AD_PARAM_NAMES)}
    i0, i1 = name_idx[pair[0]], name_idx[pair[1]]
    base = AD_PARAM_VALUES.copy()
    n = int(round(t_max / dt))
    grid_np = (np.arange(n + 1) * dt).astype(np.float64)
    u_np = np.asarray(_dose_grid(jnp.asarray(grid_np[:-1]), dose, DOSE_WINDOW))
    x0_np = AD_X0.copy()
    biom_np = np.asarray(biomarkers)

    def observe(theta: Array, phi: Array) -> Array:
        p = jnp.asarray(base, theta.dtype)
        p = p.at[i0].set(jnp.exp(theta[0])).at[i1].set(jnp.exp(theta[1]))
        grid_t = jnp.asarray(grid_np, theta.dtype)
        u_grid = jnp.asarray(u_np, theta.dtype)
        x0 = jnp.asarray(x0_np, theta.dtype)
        traj = _rk4_full(p, x0, grid_t[:-1], u_grid, dt)
        return _observe_at(traj, grid_t, phi, jnp.asarray(biom_np))

    theta0 = np.array([np.log(base[i0]), np.log(base[i1])], dtype=np.float64)
    tgt_name = f"log_{target}"
    _tname = {pair[0]: f"log_{pair[0]}", pair[1]: f"log_{pair[1]}"}
    return DesignProblem(
        observe=observe,
        theta0=theta0,
        param_names=(_tname[pair[0]], _tname[pair[1]]),
        sigma=sigma,
        phi_bounds=(t_min, t_max),
        meta={"model": "ad_qsp", "pair": pair, "target": tgt_name, "dose": dose,
              "dose_window": DOSE_WINDOW, "t_max": t_max, "dt": dt, "biomarkers": biomarkers,
              "x0": x0_np},
    )
