"""Figure-code preservation — the Claude Science grain (``design`` §4).

Every figure NUDGE emits carries (or is regenerable from) its exact generating code, so
a scientist can reproduce or modify it. For ``out="fig.png"`` the render pipeline writes
three files: ``fig.png`` (the image), ``fig.data.json`` (the numbers the figure was drawn
from — the fit's OUTPUT, not the raw screen), and ``fig.py`` (a standalone, deterministic
script that replays the SAME plotting code over the SAME numbers — no re-fit, no JAX, no
data download). ``self_contained=True`` inlines the data as a base64 blob inside
``fig.py`` so a single file regenerates the figure (the mode to hand to a Claude Artifact).
"""

from __future__ import annotations

import base64
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _git_sha() -> str:
    import subprocess

    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
        sha = out.stdout.strip()
        return sha or "unknown"
    except Exception:  # pragma: no cover - git absent / not a repo
        return "unknown"


def _nudge_version() -> str:
    try:
        from nudge import __version__

        return __version__
    except Exception:  # pragma: no cover
        return "unknown"


def _header(png_name: str, cli_call: str | None) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Generated by NUDGE viz — regenerates {png_name} exactly "
        "(no re-fit; deterministic).",
        f"# nudge {_nudge_version()} · git {_git_sha()} · {stamp}",
    ]
    if cli_call:
        lines.append(f"# call: {cli_call}")
    lines.append(
        "# It replays the SAME plotting code over the SAME numbers (the fit's OUTPUT),"
    )
    lines.append("# so the figure — including any abstention overlay — is reproduced.")
    return "\n".join(lines)


def emit_code(
    data: dict[str, Any],
    png_path: str,
    *,
    self_contained: bool = False,
    cli_call: str | None = None,
) -> tuple[str, str | None]:
    """Write the regenerating ``fig.py`` (+ ``fig.data.json`` unless self-contained).

    ``data`` is the figure-data dict (kind + panels + the numbers). Returns
    ``(code_path, data_path)`` — ``data_path`` is ``None`` in ``self_contained`` mode
    (the data lives inline in the script). The emitted script calls
    ``nudge.viz.render(data, out=..., emit_code=False)`` — the dual-input dict path — so
    it reproduces the exact figure without re-fitting.
    """
    png = Path(png_path)
    stem = png.stem
    code_path = png.with_name(f"{stem}.py")
    header = _header(png.name, cli_call)

    if self_contained:
        blob = base64.b64encode(
            json.dumps(data, sort_keys=True).encode("utf-8")
        ).decode("ascii")
        script = (
            f"{header}\n"
            "import base64\n"
            "import json\n\n"
            "import nudge.viz as viz\n\n"
            f'_DATA = "{blob}"\n'
            "data = json.loads(base64.b64decode(_DATA))\n"
            f'viz.render(data, out="{png.name}", emit_code=False)\n'
        )
        code_path.write_text(script, encoding="utf-8")
        return str(code_path), None

    data_path = png.with_name(f"{stem}.data.json")
    data_path.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")
    script = (
        f"{header}\n"
        "import json\n\n"
        "import nudge.viz as viz\n\n"
        f'with open("{data_path.name}") as _fh:\n'
        "    data = json.load(_fh)\n"
        f'viz.render(data, out="{png.name}", emit_code=False)\n'
    )
    code_path.write_text(script, encoding="utf-8")
    return str(code_path), str(data_path)
